language: elixir
notifications:
  recipients:
    - klaus.alfert@googlemail.com
otp_release:
  - 17.4
elixir:
  - 1.0.0
  - 1.0.5
  - 1.1.0-rc.0
install:
  - mix local.hex --force
script: "MIX_ENV=test mix do deps.get, deps.compile, test --cover"
